//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KServer.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address seems invalid..
        /// </summary>
        internal static string ERR_BAD_EMAIL {
            get {
                return ResourceManager.GetString("ERR_BAD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server received some bad input, please try again..
        /// </summary>
        internal static string ERR_BAD_SERVER_INPUT {
            get {
                return ResourceManager.GetString("ERR_BAD_SERVER_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is blank..
        /// </summary>
        internal static string ERR_CRED_BLANK {
            get {
                return ResourceManager.GetString("ERR_CRED_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is too long, please shorten to &lt;= 20 characters..
        /// </summary>
        internal static string ERR_CRED_LONG {
            get {
                return ResourceManager.GetString("ERR_CRED_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not available..
        /// </summary>
        internal static string ERR_CRED_TAKEN {
            get {
                return ResourceManager.GetString("ERR_CRED_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        internal static string ERR_CRED_WRONG {
            get {
                return ResourceManager.GetString("ERR_CRED_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That song already exists in this playlist..
        /// </summary>
        internal static string ERR_PLYLST_DUP_SONG {
            get {
                return ResourceManager.GetString("ERR_PLYLST_DUP_SONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlists&apos;s name is too long, please shorten to &lt;= 20 characters..
        /// </summary>
        internal static string ERR_PLYLST_NAME_LONG {
            get {
                return ResourceManager.GetString("ERR_PLYLST_NAME_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a venue associated with the scanned QR code..
        /// </summary>
        internal static string ERR_QR_BAD {
            get {
                return ResourceManager.GetString("ERR_QR_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mobioke server encountered an error, please try again later..
        /// </summary>
        internal static string ERR_SERVER {
            get {
                return ResourceManager.GetString("ERR_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in..
        /// </summary>
        internal static string ERR_STATUS_ALREADY_IN {
            get {
                return ResourceManager.GetString("ERR_STATUS_ALREADY_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged out..
        /// </summary>
        internal static string ERR_STATUS_ALREADY_OUT {
            get {
                return ResourceManager.GetString("ERR_STATUS_ALREADY_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in..
        /// </summary>
        internal static string ERR_STATUS_IS_NOT_IN {
            get {
                return ResourceManager.GetString("ERR_STATUS_IS_NOT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Venue is not running a Mobioke session..
        /// </summary>
        internal static string ERR_VENUE_NO_SESSION {
            get {
                return ResourceManager.GetString("ERR_VENUE_NO_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no song requests..
        /// </summary>
        internal static string MSG_NO_SONG_REQUESTS {
            get {
                return ResourceManager.GetString("MSG_NO_SONG_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a given song..
        /// </summary>
        internal static string MSG_SONG_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_SONG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned from this venue..
        /// </summary>
        internal static string MSG_USER_BANNED {
            get {
                return ResourceManager.GetString("MSG_USER_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no song requests..
        /// </summary>
        internal static string MSG_USER_NO_SONG_REQUESTS {
            get {
                return ResourceManager.GetString("MSG_USER_NO_SONG_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in the queue..
        /// </summary>
        internal static string MSG_USER_NOT_IN_QUEUE {
            get {
                return ResourceManager.GetString("MSG_USER_NOT_IN_QUEUE", resourceCulture);
            }
        }
    }
}
