//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KServer.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #~Q.
        /// </summary>
        internal static string DELIMINATOR {
            get {
                return ResourceManager.GetString("DELIMINATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobioke@live.com.
        /// </summary>
        internal static string EMAIL_ADR {
            get {
                return ResourceManager.GetString("EMAIL_ADR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamWarpZone.
        /// </summary>
        internal static string EMAIL_PSWD {
            get {
                return ResourceManager.GetString("EMAIL_PSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyCGoaZFOiMsz0Hxo5_52y1EU0aNUimeYbw.
        /// </summary>
        internal static string GCM_APPLICATION_ID {
            get {
                return ResourceManager.GetString("GCM_APPLICATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 599874388677.
        /// </summary>
        internal static string GCM_SENDER_ID {
            get {
                return ResourceManager.GetString("GCM_SENDER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random_weighted.
        /// </summary>
        internal static string SNG_SGGST_MTHD {
            get {
                return ResourceManager.GetString("SNG_SGGST_MTHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string TIME_BETWEEN_REQUESTS {
            get {
                return ResourceManager.GetString("TIME_BETWEEN_REQUESTS", resourceCulture);
            }
        }
    }
}
