//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiokeWebSite.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error {
            get {
                return this.errorField;
            }
            set {
                if ((this.errorField.Equals(value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class Venue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string venueAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int venueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string venueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string venueAddress {
            get {
                return this.venueAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.venueAddressField, value) != true)) {
                    this.venueAddressField = value;
                    this.RaisePropertyChanged("venueAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int venueID {
            get {
                return this.venueIDField;
            }
            set {
                if ((this.venueIDField.Equals(value) != true)) {
                    this.venueIDField = value;
                    this.RaisePropertyChanged("venueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string venueName {
            get {
                return this.venueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.venueNameField, value) != true)) {
                    this.venueNameField = value;
                    this.RaisePropertyChanged("venueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebsite")]
    public interface IWebsite {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/SendEmailWithUsername", ReplyAction="http://tempuri.org/IWebsite/SendEmailWithUsernameResponse")]
        MobiokeWebSite.ServiceReference1.Response SendEmailWithUsername(string email, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/SendEmailWithUsername", ReplyAction="http://tempuri.org/IWebsite/SendEmailWithUsernameResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> SendEmailWithUsernameAsync(string email, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/StartPasswordReset", ReplyAction="http://tempuri.org/IWebsite/StartPasswordResetResponse")]
        MobiokeWebSite.ServiceReference1.StartPasswordResetResponse StartPasswordReset(MobiokeWebSite.ServiceReference1.StartPasswordResetRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/StartPasswordReset", ReplyAction="http://tempuri.org/IWebsite/StartPasswordResetResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.StartPasswordResetResponse> StartPasswordResetAsync(MobiokeWebSite.ServiceReference1.StartPasswordResetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/CompletePasswordReset", ReplyAction="http://tempuri.org/IWebsite/CompletePasswordResetResponse")]
        MobiokeWebSite.ServiceReference1.Response CompletePasswordReset(string key, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/CompletePasswordReset", ReplyAction="http://tempuri.org/IWebsite/CompletePasswordResetResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> CompletePasswordResetAsync(string key, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/ChangePassword", ReplyAction="http://tempuri.org/IWebsite/ChangePasswordResponse")]
        MobiokeWebSite.ServiceReference1.Response ChangePassword(string username, string oldPassword, string newPassword, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/ChangePassword", ReplyAction="http://tempuri.org/IWebsite/ChangePasswordResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> ChangePasswordAsync(string username, string oldPassword, string newPassword, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/ChangeEmail", ReplyAction="http://tempuri.org/IWebsite/ChangeEmailResponse")]
        MobiokeWebSite.ServiceReference1.Response ChangeEmail(string username, string password, string newEmail, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/ChangeEmail", ReplyAction="http://tempuri.org/IWebsite/ChangeEmailResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> ChangeEmailAsync(string username, string password, string newEmail, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/DJSignUp", ReplyAction="http://tempuri.org/IWebsite/DJSignUpResponse")]
        MobiokeWebSite.ServiceReference1.Response DJSignUp(string username, string password, MobiokeWebSite.ServiceReference1.Venue venue, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/DJSignUp", ReplyAction="http://tempuri.org/IWebsite/DJSignUpResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> DJSignUpAsync(string username, string password, MobiokeWebSite.ServiceReference1.Venue venue, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/MobileSignUp", ReplyAction="http://tempuri.org/IWebsite/MobileSignUpResponse")]
        MobiokeWebSite.ServiceReference1.Response MobileSignUp(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/MobileSignUp", ReplyAction="http://tempuri.org/IWebsite/MobileSignUpResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> MobileSignUpAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/EnableDisableRegistration", ReplyAction="http://tempuri.org/IWebsite/EnableDisableRegistrationResponse")]
        MobiokeWebSite.ServiceReference1.Response EnableDisableRegistration(bool enableRegistration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/EnableDisableRegistration", ReplyAction="http://tempuri.org/IWebsite/EnableDisableRegistrationResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> EnableDisableRegistrationAsync(bool enableRegistration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/IsRegistrationAllowed", ReplyAction="http://tempuri.org/IWebsite/IsRegistrationAllowedResponse")]
        MobiokeWebSite.ServiceReference1.IsRegistrationAllowedResponse IsRegistrationAllowed(MobiokeWebSite.ServiceReference1.IsRegistrationAllowedRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsite/IsRegistrationAllowed", ReplyAction="http://tempuri.org/IWebsite/IsRegistrationAllowedResponse")]
        System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.IsRegistrationAllowedResponse> IsRegistrationAllowedAsync(MobiokeWebSite.ServiceReference1.IsRegistrationAllowedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartPasswordReset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartPasswordResetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string role;
        
        public StartPasswordResetRequest() {
        }
        
        public StartPasswordResetRequest(string email, string role) {
            this.email = email;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartPasswordResetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartPasswordResetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobiokeWebSite.ServiceReference1.Response StartPasswordResetResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string key;
        
        public StartPasswordResetResponse() {
        }
        
        public StartPasswordResetResponse(MobiokeWebSite.ServiceReference1.Response StartPasswordResetResult, string key) {
            this.StartPasswordResetResult = StartPasswordResetResult;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsRegistrationAllowed", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsRegistrationAllowedRequest {
        
        public IsRegistrationAllowedRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsRegistrationAllowedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsRegistrationAllowedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobiokeWebSite.ServiceReference1.Response IsRegistrationAllowedResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool registrationAllowed;
        
        public IsRegistrationAllowedResponse() {
        }
        
        public IsRegistrationAllowedResponse(MobiokeWebSite.ServiceReference1.Response IsRegistrationAllowedResult, bool registrationAllowed) {
            this.IsRegistrationAllowedResult = IsRegistrationAllowedResult;
            this.registrationAllowed = registrationAllowed;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebsiteChannel : MobiokeWebSite.ServiceReference1.IWebsite, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebsiteClient : System.ServiceModel.ClientBase<MobiokeWebSite.ServiceReference1.IWebsite>, MobiokeWebSite.ServiceReference1.IWebsite {
        
        public WebsiteClient() {
        }
        
        public WebsiteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebsiteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsiteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsiteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MobiokeWebSite.ServiceReference1.Response SendEmailWithUsername(string email, string role) {
            return base.Channel.SendEmailWithUsername(email, role);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> SendEmailWithUsernameAsync(string email, string role) {
            return base.Channel.SendEmailWithUsernameAsync(email, role);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobiokeWebSite.ServiceReference1.StartPasswordResetResponse MobiokeWebSite.ServiceReference1.IWebsite.StartPasswordReset(MobiokeWebSite.ServiceReference1.StartPasswordResetRequest request) {
            return base.Channel.StartPasswordReset(request);
        }
        
        public MobiokeWebSite.ServiceReference1.Response StartPasswordReset(string email, string role, out string key) {
            MobiokeWebSite.ServiceReference1.StartPasswordResetRequest inValue = new MobiokeWebSite.ServiceReference1.StartPasswordResetRequest();
            inValue.email = email;
            inValue.role = role;
            MobiokeWebSite.ServiceReference1.StartPasswordResetResponse retVal = ((MobiokeWebSite.ServiceReference1.IWebsite)(this)).StartPasswordReset(inValue);
            key = retVal.key;
            return retVal.StartPasswordResetResult;
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.StartPasswordResetResponse> StartPasswordResetAsync(MobiokeWebSite.ServiceReference1.StartPasswordResetRequest request) {
            return base.Channel.StartPasswordResetAsync(request);
        }
        
        public MobiokeWebSite.ServiceReference1.Response CompletePasswordReset(string key, string newPassword) {
            return base.Channel.CompletePasswordReset(key, newPassword);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> CompletePasswordResetAsync(string key, string newPassword) {
            return base.Channel.CompletePasswordResetAsync(key, newPassword);
        }
        
        public MobiokeWebSite.ServiceReference1.Response ChangePassword(string username, string oldPassword, string newPassword, string role) {
            return base.Channel.ChangePassword(username, oldPassword, newPassword, role);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> ChangePasswordAsync(string username, string oldPassword, string newPassword, string role) {
            return base.Channel.ChangePasswordAsync(username, oldPassword, newPassword, role);
        }
        
        public MobiokeWebSite.ServiceReference1.Response ChangeEmail(string username, string password, string newEmail, string role) {
            return base.Channel.ChangeEmail(username, password, newEmail, role);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> ChangeEmailAsync(string username, string password, string newEmail, string role) {
            return base.Channel.ChangeEmailAsync(username, password, newEmail, role);
        }
        
        public MobiokeWebSite.ServiceReference1.Response DJSignUp(string username, string password, MobiokeWebSite.ServiceReference1.Venue venue, string email) {
            return base.Channel.DJSignUp(username, password, venue, email);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> DJSignUpAsync(string username, string password, MobiokeWebSite.ServiceReference1.Venue venue, string email) {
            return base.Channel.DJSignUpAsync(username, password, venue, email);
        }
        
        public MobiokeWebSite.ServiceReference1.Response MobileSignUp(string username, string password, string email) {
            return base.Channel.MobileSignUp(username, password, email);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> MobileSignUpAsync(string username, string password, string email) {
            return base.Channel.MobileSignUpAsync(username, password, email);
        }
        
        public MobiokeWebSite.ServiceReference1.Response EnableDisableRegistration(bool enableRegistration) {
            return base.Channel.EnableDisableRegistration(enableRegistration);
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.Response> EnableDisableRegistrationAsync(bool enableRegistration) {
            return base.Channel.EnableDisableRegistrationAsync(enableRegistration);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobiokeWebSite.ServiceReference1.IsRegistrationAllowedResponse MobiokeWebSite.ServiceReference1.IWebsite.IsRegistrationAllowed(MobiokeWebSite.ServiceReference1.IsRegistrationAllowedRequest request) {
            return base.Channel.IsRegistrationAllowed(request);
        }
        
        public MobiokeWebSite.ServiceReference1.Response IsRegistrationAllowed(out bool registrationAllowed) {
            MobiokeWebSite.ServiceReference1.IsRegistrationAllowedRequest inValue = new MobiokeWebSite.ServiceReference1.IsRegistrationAllowedRequest();
            MobiokeWebSite.ServiceReference1.IsRegistrationAllowedResponse retVal = ((MobiokeWebSite.ServiceReference1.IWebsite)(this)).IsRegistrationAllowed(inValue);
            registrationAllowed = retVal.registrationAllowed;
            return retVal.IsRegistrationAllowedResult;
        }
        
        public System.Threading.Tasks.Task<MobiokeWebSite.ServiceReference1.IsRegistrationAllowedResponse> IsRegistrationAllowedAsync(MobiokeWebSite.ServiceReference1.IsRegistrationAllowedRequest request) {
            return base.Channel.IsRegistrationAllowedAsync(request);
        }
    }
}
