//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JakubTestClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error {
            get {
                return this.errorField;
            }
            set {
                if ((this.errorField.Equals(value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogInResponse", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class LogInResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JakubTestClient.ServiceReference1.User userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error {
            get {
                return this.errorField;
            }
            set {
                if ((this.errorField.Equals(value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JakubTestClient.ServiceReference1.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userKey {
            get {
                return this.userKeyField;
            }
            set {
                if ((this.userKeyField.Equals(value) != true)) {
                    this.userKeyField = value;
                    this.RaisePropertyChanged("userKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int venueIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                if ((this.sessionIDField.Equals(value) != true)) {
                    this.sessionIDField = value;
                    this.RaisePropertyChanged("sessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int venueID {
            get {
                return this.venueIDField;
            }
            set {
                if ((this.venueIDField.Equals(value) != true)) {
                    this.venueIDField = value;
                    this.RaisePropertyChanged("venueID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Song", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class Song : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string artistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathOnDiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string artist {
            get {
                return this.artistField;
            }
            set {
                if ((object.ReferenceEquals(this.artistField, value) != true)) {
                    this.artistField = value;
                    this.RaisePropertyChanged("artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pathOnDisk {
            get {
                return this.pathOnDiskField;
            }
            set {
                if ((object.ReferenceEquals(this.pathOnDiskField, value) != true)) {
                    this.pathOnDiskField = value;
                    this.RaisePropertyChanged("pathOnDisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongRequest", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class SongRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int songIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JakubTestClient.ServiceReference1.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int songID {
            get {
                return this.songIDField;
            }
            set {
                if ((this.songIDField.Equals(value) != true)) {
                    this.songIDField = value;
                    this.RaisePropertyChanged("songID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JakubTestClient.ServiceReference1.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queueSinger", Namespace="http://schemas.datacontract.org/2004/07/KServer")]
    [System.SerializableAttribute()]
    public partial class queueSinger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JakubTestClient.ServiceReference1.Song[] songsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JakubTestClient.ServiceReference1.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JakubTestClient.ServiceReference1.Song[] songs {
            get {
                return this.songsField;
            }
            set {
                if ((object.ReferenceEquals(this.songsField, value) != true)) {
                    this.songsField = value;
                    this.RaisePropertyChanged("songs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JakubTestClient.ServiceReference1.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1", CallbackContract=typeof(JakubTestClient.ServiceReference1.IService1Callback))]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJSignUp", ReplyAction="http://tempuri.org/IService1/DJSignUpResponse")]
        JakubTestClient.ServiceReference1.Response DJSignUp(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJSignIn", ReplyAction="http://tempuri.org/IService1/DJSignInResponse")]
        JakubTestClient.ServiceReference1.LogInResponse DJSignIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJSignOut", ReplyAction="http://tempuri.org/IService1/DJSignOutResponse")]
        JakubTestClient.ServiceReference1.Response DJSignOut(long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJCreateSession", ReplyAction="http://tempuri.org/IService1/DJCreateSessionResponse")]
        JakubTestClient.ServiceReference1.Session DJCreateSession(long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJAddSongs", ReplyAction="http://tempuri.org/IService1/DJAddSongsResponse")]
        JakubTestClient.ServiceReference1.Response DJAddSongs(JakubTestClient.ServiceReference1.Song[] songs, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJRemoveSongs", ReplyAction="http://tempuri.org/IService1/DJRemoveSongsResponse")]
        JakubTestClient.ServiceReference1.Response DJRemoveSongs(JakubTestClient.ServiceReference1.Song[] songs, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJAddQueue", ReplyAction="http://tempuri.org/IService1/DJAddQueueResponse")]
        JakubTestClient.ServiceReference1.Response DJAddQueue(JakubTestClient.ServiceReference1.SongRequest sr, int queueIndex, int sessionID, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJRemoveSongRequest", ReplyAction="http://tempuri.org/IService1/DJRemoveSongRequestResponse")]
        JakubTestClient.ServiceReference1.Response DJRemoveSongRequest(JakubTestClient.ServiceReference1.SongRequest sr, int sessionID, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJChangeSongRequest", ReplyAction="http://tempuri.org/IService1/DJChangeSongRequestResponse")]
        JakubTestClient.ServiceReference1.Response DJChangeSongRequest(JakubTestClient.ServiceReference1.SongRequest newSR, JakubTestClient.ServiceReference1.SongRequest oldSR, int sessionID, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJRemoveUser", ReplyAction="http://tempuri.org/IService1/DJRemoveUserResponse")]
        JakubTestClient.ServiceReference1.Response DJRemoveUser(JakubTestClient.ServiceReference1.SongRequest newSR, JakubTestClient.ServiceReference1.SongRequest oldSR, int sessionID, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJMoveUser", ReplyAction="http://tempuri.org/IService1/DJMoveUserResponse")]
        JakubTestClient.ServiceReference1.Response DJMoveUser(int userID, int sessionID, long DJKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientSignUp", ReplyAction="http://tempuri.org/IService1/ClientSignUpResponse")]
        JakubTestClient.ServiceReference1.Response ClientSignUp(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientSignIn", ReplyAction="http://tempuri.org/IService1/ClientSignInResponse")]
        JakubTestClient.ServiceReference1.LogInResponse ClientSignIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientSignOut", ReplyAction="http://tempuri.org/IService1/ClientSignOutResponse")]
        JakubTestClient.ServiceReference1.Response ClientSignOut(long userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Search", ReplyAction="http://tempuri.org/IService1/SearchResponse")]
        JakubTestClient.ServiceReference1.Song[] Search(string title, string artist, int venueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Browse", ReplyAction="http://tempuri.org/IService1/BrowseResponse")]
        JakubTestClient.ServiceReference1.Song[] Browse(char firstLetter, bool isArtist, int start, int count, int venueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientSongRequest", ReplyAction="http://tempuri.org/IService1/ClientSongRequestResponse")]
        JakubTestClient.ServiceReference1.Response ClientSongRequest(JakubTestClient.ServiceReference1.SongRequest sr, long userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientRemoveSongRequest", ReplyAction="http://tempuri.org/IService1/ClientRemoveSongRequestResponse")]
        JakubTestClient.ServiceReference1.Response ClientRemoveSongRequest(JakubTestClient.ServiceReference1.SongRequest sr, long userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientChangeSongRequest", ReplyAction="http://tempuri.org/IService1/ClientChangeSongRequestResponse")]
        JakubTestClient.ServiceReference1.Response ClientChangeSongRequest(int prevSongID, JakubTestClient.ServiceReference1.SongRequest sr, long userKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Callback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DJQueueChanged", ReplyAction="http://tempuri.org/IService1/DJQueueChangedResponse")]
        JakubTestClient.ServiceReference1.Response DJQueueChanged(JakubTestClient.ServiceReference1.queueSinger[] queue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : JakubTestClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.DuplexClientBase<JakubTestClient.ServiceReference1.IService1>, JakubTestClient.ServiceReference1.IService1 {
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public JakubTestClient.ServiceReference1.Response DJSignUp(string userName, string password) {
            return base.Channel.DJSignUp(userName, password);
        }
        
        public JakubTestClient.ServiceReference1.LogInResponse DJSignIn(string userName, string password) {
            return base.Channel.DJSignIn(userName, password);
        }
        
        public JakubTestClient.ServiceReference1.Response DJSignOut(long DJKey) {
            return base.Channel.DJSignOut(DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Session DJCreateSession(long DJKey) {
            return base.Channel.DJCreateSession(DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJAddSongs(JakubTestClient.ServiceReference1.Song[] songs, long DJKey) {
            return base.Channel.DJAddSongs(songs, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJRemoveSongs(JakubTestClient.ServiceReference1.Song[] songs, long DJKey) {
            return base.Channel.DJRemoveSongs(songs, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJAddQueue(JakubTestClient.ServiceReference1.SongRequest sr, int queueIndex, int sessionID, long DJKey) {
            return base.Channel.DJAddQueue(sr, queueIndex, sessionID, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJRemoveSongRequest(JakubTestClient.ServiceReference1.SongRequest sr, int sessionID, long DJKey) {
            return base.Channel.DJRemoveSongRequest(sr, sessionID, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJChangeSongRequest(JakubTestClient.ServiceReference1.SongRequest newSR, JakubTestClient.ServiceReference1.SongRequest oldSR, int sessionID, long DJKey) {
            return base.Channel.DJChangeSongRequest(newSR, oldSR, sessionID, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJRemoveUser(JakubTestClient.ServiceReference1.SongRequest newSR, JakubTestClient.ServiceReference1.SongRequest oldSR, int sessionID, long DJKey) {
            return base.Channel.DJRemoveUser(newSR, oldSR, sessionID, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response DJMoveUser(int userID, int sessionID, long DJKey) {
            return base.Channel.DJMoveUser(userID, sessionID, DJKey);
        }
        
        public JakubTestClient.ServiceReference1.Response ClientSignUp(string userName, string password) {
            return base.Channel.ClientSignUp(userName, password);
        }
        
        public JakubTestClient.ServiceReference1.LogInResponse ClientSignIn(string userName, string password) {
            return base.Channel.ClientSignIn(userName, password);
        }
        
        public JakubTestClient.ServiceReference1.Response ClientSignOut(long userKey) {
            return base.Channel.ClientSignOut(userKey);
        }
        
        public JakubTestClient.ServiceReference1.Song[] Search(string title, string artist, int venueID) {
            return base.Channel.Search(title, artist, venueID);
        }
        
        public JakubTestClient.ServiceReference1.Song[] Browse(char firstLetter, bool isArtist, int start, int count, int venueID) {
            return base.Channel.Browse(firstLetter, isArtist, start, count, venueID);
        }
        
        public JakubTestClient.ServiceReference1.Response ClientSongRequest(JakubTestClient.ServiceReference1.SongRequest sr, long userKey) {
            return base.Channel.ClientSongRequest(sr, userKey);
        }
        
        public JakubTestClient.ServiceReference1.Response ClientRemoveSongRequest(JakubTestClient.ServiceReference1.SongRequest sr, long userKey) {
            return base.Channel.ClientRemoveSongRequest(sr, userKey);
        }
        
        public JakubTestClient.ServiceReference1.Response ClientChangeSongRequest(int prevSongID, JakubTestClient.ServiceReference1.SongRequest sr, long userKey) {
            return base.Channel.ClientChangeSongRequest(prevSongID, sr, userKey);
        }
    }
}
